### ISSUE TITLE
Scan based on string (--github-string)

### ISSUE THREAD

**Issue by Regala** [N0MoreSecr3ts/wraith#114]
Hi!

Wondering if it would be possible to scan based a number of strings. An often example is searching for an internal domain, e.g. `uberinternal.com`. This might be a huge scan, but can definitely pay off.  
(maybe this feature can be triggered already, not sure?)

Thanks!

**Comment by mattyjones** [comment]
You can add it as a regex in the signatures file you pull locally. If it is common, or general enough it can be added to the signatures repo.

**Comment by Regala** [comment]
Hum let me rephrase this then, if you were trying to scan Uber repos for secrets, particularly those who had that `uberinternal.com` how would you do it? 

Thanks!

**Comment by circleous** [comment]
You can use `PartContent` if it's a string inside a file,

```yaml
PatternSignatures:
    -
        part: PartContent
        match: '(?i)uberinternal\.com'
        description: 'Contains uberinternal.com'
        signatureid: '02024b46cfabc3c5b0900fd4cbff6a0b'
        enable: 1
        entropy: 3.5
```
